name: dynamic_bounce
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.1.1+9

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^5.6.3
  collection: ^1.19.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.3.0
  firebase_analytics: ^11.6.0
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_crashlytics: ^4.3.10
  flame: ^1.23.0
  flame_riverpod: ^5.4.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  intl: any
  path: ^1.9.0
  riverpod_annotation: ^2.6.1
  sqflite: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.2
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  generate: true
